[package]
name = "midna"
version = "0.1.0"
authors = ["Alexander Kluth <deralex@cpan.org>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
clap = "2.32.0"
colored = "1.6.1"
serde_json = "1.0.34"
dirs = "1.0.4"